### ISSUE TITLE
New gganimate api

### ISSUE THREAD

**Issue by jjn13** [DataSlingers/clustRviz#14]
I attempted to install the most recent version of gganimate (https://github.com/thomasp85/gganimate/) on one of my linux machines:

devtools::install_github('thomasp85/gganimate')

but this fails due to gifski dependency (https://github.com/r-rust/gifski). Trying to install this via:

devtools::install_github("r-rust/gifski")

asks me install rust environment via:

sudo apt-get install cargo

which also fails, but can be fixed by adding an external repo.

This is not necessarily a no-go, but we will be requiring windows/linux/mac users to have rust; the situation then seems similar to the SuperLU difficulties we encountered w/ RcppArmadillo.

Just wanted to check if this is desirable before translating gganimate to the new API.

**Comment by michaelweylandt** [comment]
I *think* it's ok -- CRAN distributes binaries, so non-Linux users won't need `cargo` or `rustc`. Agreed it's a pain for Linux users, but I think it's unavoidable. The old `gganimate` won't be around long-term.

**Comment by jjn13** [comment]
Cool, I agree. I don't think the package install will be overly burdensome.

**Comment by jjn13** [comment]
See https://github.com/DataSlingers/clustRviz/pull/47 for pull request

**Comment by michaelweylandt** [comment]
Closed via #47
