### ISSUE TITLE
Disable Back-Tracking by Default

### ISSUE THREAD

**Issue by michaelweylandt** [DataSlingers/clustRviz#76]
@agenevera thinks that the backtracking versions (`CARP-VIZ` and `CBASS-VIZ`) are too expensive to use by default on larger data sets. 

@jjn13 Thoughts on changing the default to disable back-tracking?

**Comment by jjn13** [comment]
Sure, I think making the default the fastest possible alg. would be a good choice.

**Comment by michaelweylandt** [comment]
Ok. In the short term, I’ll change the defaults of `alg.type`

In the medium term, I want to refactor the c++ to support a back-tracking
exact solve and instead expose `exact` and `backtrack` arguments (both
`FALSE` by default)

**Comment by michaelweylandt** [comment]
Closed by #79
