### ISSUE TITLE
Fails with Uniform Weights

### ISSUE THREAD

**Issue by michaelweylandt** [DataSlingers/clustRviz#8]
This fails somewhere in the dendrogram reconstruction code: 

`CARP(presidential_speech, weights = rep(1, 44 * 43 / 2))`

I've confirmed that this fails with a commit from before I touched the C++ code, so I don't think it's anything I did. 

@jjn13 - Can you take a look? It might be in the back-tracking: `alg.type="carp"` seems to fix it.

**Comment by jjn13** [comment]
I've submitted pull request https://github.com/DataSlingers/clustRviz/pull/39 to address.

**Comment by michaelweylandt** [comment]
Closed in #39
