### ISSUE TITLE
Hardcoded paths to strip and uname

### ISSUE THREAD

**Issue by jbedo** [DataSlingers/clustRviz#86]
In Makevars strip and uname are assumed to be in /usr/bin and /bin respectively. This is not the case on some systems (e.g., NixOS), requiring patching to remove the hardcoded paths.

**Comment by michaelweylandt** [comment]
Hi @jbedo, thanks for the report. 

I'm not 100% sure why a patch would be needed, since any invocation of `strip` or `uname` is preceeded by `test -e`. Thoughts? 

I'd certainly be happy to restructure this in a more cross-platform way: what would be best for NixOS?

**Comment by jbedo** [comment]
Your right, they are preceded by test, apologies for not reading the source :).

The bug here is that Bourne shell conjunction is && not &. The following patch resolves it for me:

```
diff --git a/src/Makevars b/src/Makevars
index 076a2eb..897c911 100644
--- a/src/Makevars
+++ b/src/Makevars
@@ -2,7 +2,7 @@ CXX_STD = CXX11
 PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)

 strip: $(SHLIB)
-       if test -e "/usr/bin/strip" & test -e "/bin/uname" & [[ `uname` == "Linux" ]] ; then /usr/bin/strip --strip-debug *.o *.so; fi
-       if test -e "/usr/bin/strip" & test -e "/usr/bin/uname" & [[ `uname` == "Darwin" ]] ; then /usr/bin/strip -S *.o *.so; fi
+       if test -e "/usr/bin/strip" && test -e "/bin/uname" && [[ `uname` == "Linux" ]] ; then /usr/bin/strip --strip-debug *.o *.so; fi
+       if test -e "/usr/bin/strip" && test -e "/usr/bin/uname" && [[ `uname` == "Darwin" ]] ; then /usr/bin/strip -S *.o *.so; fi

 .phony: strip
```

One other thing I notice is that `/bin/uname` is tested but `uname` is executed (i.e., whatever is in the path). Maybe the whole thing would be simplified to something like (I haven't tested it):
```
[[ `uname` == "Linux" ]] && strip --strip-debug *.o *.so || true
[[ `uname` == "Darwin" ]] && strip -S *.o *.so || true
```

**Comment by michaelweylandt** [comment]
That seems reasonable. I've committed a variant of that (but keeping the `test -e strip` check) as PR #87.

**Comment by michaelweylandt** [comment]
Hi @jbedo 

I've merged the fix into `develop` and it's been built in `master.` Can you confirm this fixed version looks for you / on NixOS?

Michael

**Comment by jbedo** [comment]
Sorry for delay: confirmed master branch works fine now. Thanks!

**Comment by michaelweylandt** [comment]
Glad to hear -- thanks!
